### ISSUE TITLE
Build fails on Windows10

### ISSUE THREAD

**Issue by matdander** [emmt/OptimPackNextGen.jl#4]
When trying to install and build on windows 10, a problem arises with installing  libcobyla. I don't see this when building on Mac OS. 

> julia> Pkg.clone("https://github.com/emmt/OptimPackNextGen.jl.git")
  Updating git-repo `https://github.com/emmt/OptimPackNextGen.jl.git`
[ Info: Path `C:\Users\$$$$$\.julia\dev\OptimPackNextGen` exists and looks like the correct package, using existing path
 Resolving package versions...
  Updating `C:\Users\$$$$$\.julia\environments\v1.3\Project.toml`
 [no changes]
  Updating `C:\Users\$$$$$\.julia\environments\v1.3\Manifest.toml`
 [no changes]
  Building OptimPackNextGen → `C:\Users\$$$$$\.julia\dev\OptimPackNextGen\deps\build.log`
┌ Error: Error building `OptimPackNextGen`:
│ ERROR: LoadError: None of the selected providers can install dependency libcobyla.
│ Use BinDeps.debug(package_name) to see available providers
│
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\$$$$$\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:956
│  [3] satisfy!(::BinDeps.LibraryDependency) at C:\Users\$$$$$\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:929
│  [4] top-level scope at C:\Users\$$$$$\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:984
│  [5] include at .\boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1105
│  [7] include(::Module, ::String) at .\Base.jl:31
│  [8] include(::String) at .\client.jl:424
│  [9] top-level scope at none:5
│ in expression starting at C:\Users\$$$$$$$\.julia\dev\OptimPackNextGen\deps\build.jl:55
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649

Another issue is that the installation for LazyAlgebra fails on ArrayTools. Installing ArrayTools manually from the repo and then installing LazyAlgebra works just fine. I encountered this on both Windows 10 and Mac OS.

**Comment by emmt** [comment]
For the first issue, I have added a recipe in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) for OptimPack to build the dynamic libraries for various architectures. Some of these libraries are used by OptimPackNextGen. I however had not yet found the time to modify the installation of  OptimPackNextGen to use these libraries.  I will have a look, it may solve your problem.

For the second point, it is expected that you have to install ArrayTools manually because it is not (yet) an official Julia package.  This is explained [here](https://emmt.github.io/LazyAlgebra.jl/dev/install/#Installation-1).  Let me known if this not clear enough. I can also force installing related non-official packages in the build script but I do not like to do things that the user is not aware of.

**Comment by emmt** [comment]
I have modified [OptimPackNextGen](https://github.com/emmt/OptimPackNextGen.jl) to use [OptimPack_jll](https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl). This should fix the problem on Windows 10.

**Comment by matdander** [comment]
I have confirmed that it now builds and precompiles without error. Thank you!

**Comment by emmt** [comment]
Can you run the tests?

**Comment by matdander** [comment]
Yes, all tests passed!

**Comment by emmt** [comment]
Thanks!
